# Generated by Django 4.2.5 on 2024-02-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightevents',
            name='carousel_events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AddField(
            model_name='highlightevents',
            name='main_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_event', to='events.event'),
        ),
    ]
