# Generated by Django 4.2.5 on 2024-02-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='fonepay_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.fonepaypayment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.invoicesummary'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.stripepayment'),
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='tickets',
            field=models.ManyToManyField(related_name='invoice', to='pos.ticket'),
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
