# Generated by Django 4.2.5 on 2024-02-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultentry',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='result_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.resultlist'),
        ),
        migrations.AddField(
            model_name='prizetemplate',
            name='category_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_prizes', to='events.categorytemplate'),
        ),
        migrations.AddField(
            model_name='prize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.category'),
        ),
        migrations.AddField(
            model_name='mediaforeventtemplate',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_medias', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='mediaforevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='events.event'),
        ),
        migrations.AddField(
            model_name='mediaforcategorytemplate',
            name='category_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_category_medias', to='events.categorytemplate'),
        ),
        migrations.AddField(
            model_name='mediaforcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='events.category'),
        ),
        migrations.AddField(
            model_name='mediaforaddontemplate',
            name='addon_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_addons_medias', to='events.addontemplate'),
        ),
        migrations.AddField(
            model_name='mediaforaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='events.addon'),
        ),
        migrations.AddField(
            model_name='faqtemplate',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_faqs', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='faq',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='event_tags',
            field=models.ManyToManyField(related_name='event_templates', to='events.eventtag'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_templates', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_tags',
            field=models.ManyToManyField(related_name='events', to='events.eventtag'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='events.event'),
        ),
        migrations.AddField(
            model_name='addontemplate',
            name='addon_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.addoncategory'),
        ),
        migrations.AddField(
            model_name='addontemplate',
            name='event_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_addons', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='addon',
            name='addon_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.addoncategory'),
        ),
        migrations.AddField(
            model_name='addon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='prizetemplate',
            constraint=models.UniqueConstraint(fields=('category_template', 'rank', 'gender'), name='rank template prize constraint'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.UniqueConstraint(fields=('category', 'rank', 'gender'), name='rank prize constraint'),
        ),
    ]
